# utils/pdf_converter.py
"""
Markdown转PDF转换器
使用fpdf2库，无需系统依赖
支持中文字体、表格渲染、专业排版
"""

import os
import re
import tempfile
from datetime import datetime
from typing import Optional, List, Tuple

# 尝试导入PDF生成库
try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False

try:
    import markdown
    HAS_MARKDOWN = True
except ImportError:
    HAS_MARKDOWN = False


class FinSightPDF(FPDF):
    """
    FinSight专业研报PDF生成器
    """
    
    def __init__(self, title: str = "行业研究报告", *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.title = title
        self.chapter_num = 0
        
        # 设置页面
        self.set_auto_page_break(auto=True, margin=25)
        
        # 添加中文字体支持
        self._setup_fonts()
    
    def _setup_fonts(self):
        """设置字体"""
        # 使用内置字体，支持基本字符
        # 对于中文，使用Unicode字体
        try:
            # 尝试添加中文字体
            font_path = "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc"
            if os.path.exists(font_path):
                self.add_font("NotoSans", "", font_path, uni=True)
                self.add_font("NotoSans", "B", font_path, uni=True)
            else:
                # 使用DejaVu作为备选
                pass
        except Exception:
            pass
    
    def header(self):
        """页眉"""
        if self.page_no() > 1:  # 封面不显示页眉
            self.set_font('Helvetica', 'I', 9)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, 'FinSight AI Industry Research Report', align='C')
            self.ln(5)
            self.set_draw_color(200, 200, 200)
            self.line(10, 20, 200, 20)
            self.ln(10)
    
    def footer(self):
        """页脚"""
        if self.page_no() > 1:  # 封面不显示页脚
            self.set_y(-15)
            self.set_font('Helvetica', 'I', 9)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f'Page {self.page_no()}', align='C')
    
    def add_cover_page(self, title: str, province: str = "", industry: str = "", year: str = ""):
        """添加封面页"""
        self.add_page()
        
        # 背景色块
        self.set_fill_color(30, 64, 175)  # 深蓝色
        self.rect(0, 0, 210, 100, 'F')
        
        # 标题
        self.set_y(40)
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(255, 255, 255)
        
        # 处理标题
        report_title = title
        if province and industry and year:
            report_title = f"{year} {province} {industry}"
        
        self.multi_cell(0, 12, report_title, align='C')
        
        # 副标题
        self.set_y(70)
        self.set_font('Helvetica', '', 14)
        self.cell(0, 10, "Industry Research Report", align='C')
        
        # 分隔线
        self.set_y(110)
        self.set_draw_color(59, 130, 246)
        self.set_line_width(1)
        self.line(60, 110, 150, 110)
        
        # 报告信息
        self.set_y(130)
        self.set_font('Helvetica', '', 11)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "FinSight AI Agent", align='C')
        self.ln()
        self.cell(0, 8, f"Report Date: {datetime.now().strftime('%Y-%m-%d')}", align='C')
        self.ln()
        self.ln(20)
        
        # 免责声明
        self.set_font('Helvetica', 'I', 9)
        self.set_text_color(150, 150, 150)
        self.multi_cell(0, 5, 
            "This report is automatically generated by AI Agent for reference only.\n"
            "Investment decisions should be based on independent professional judgment.",
            align='C')
    
    def add_chapter_title(self, title: str, level: int = 1):
        """添加章节标题"""
        self.chapter_num += 1
        
        if level == 1:
            self.set_font('Helvetica', 'B', 16)
            self.set_text_color(30, 64, 175)
            self.ln(10)
            self.cell(0, 10, title, ln=True)
            self.set_draw_color(59, 130, 246)
            self.set_line_width(0.5)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(5)
        elif level == 2:
            self.set_font('Helvetica', 'B', 14)
            self.set_text_color(30, 58, 138)
            self.ln(8)
            self.cell(0, 8, title, ln=True)
            self.ln(3)
        elif level == 3:
            self.set_font('Helvetica', 'B', 12)
            self.set_text_color(30, 64, 175)
            self.ln(5)
            self.cell(0, 7, title, ln=True)
            self.ln(2)
        else:
            self.set_font('Helvetica', 'B', 11)
            self.set_text_color(71, 85, 105)
            self.ln(4)
            self.cell(0, 6, title, ln=True)
            self.ln(2)
    
    def add_paragraph(self, text: str):
        """添加段落"""
        self.set_font('Helvetica', '', 10)
        self.set_text_color(51, 51, 51)
        
        # 处理文本中的特殊格式
        text = self._process_text(text)
        
        self.multi_cell(0, 6, text)
        self.ln(3)
    
    def _process_text(self, text: str) -> str:
        """处理文本格式"""
        # 移除Markdown格式标记
        text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)  # 粗体
        text = re.sub(r'\*(.+?)\*', r'\1', text)  # 斜体
        text = re.sub(r'`(.+?)`', r'\1', text)  # 代码
        text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)  # 链接
        return text
    
    def add_table(self, headers: List[str], data: List[List[str]]):
        """添加表格"""
        self.ln(5)
        
        # 计算列宽
        page_width = 190  # A4页面宽度减去边距
        col_count = len(headers)
        col_width = page_width / col_count
        
        # 表头
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(30, 64, 175)
        self.set_text_color(255, 255, 255)
        
        for header in headers:
            self.cell(col_width, 8, str(header)[:20], border=1, fill=True, align='C')
        self.ln()
        
        # 表格数据
        self.set_font('Helvetica', '', 9)
        self.set_text_color(51, 51, 51)
        
        fill = False
        for row in data:
            if fill:
                self.set_fill_color(248, 250, 252)
            else:
                self.set_fill_color(255, 255, 255)
            
            for i, cell in enumerate(row):
                cell_text = str(cell)[:25] if cell else ""
                self.cell(col_width, 7, cell_text, border=1, fill=True, align='C')
            self.ln()
            fill = not fill
        
        self.ln(5)
    
    def add_bullet_list(self, items: List[str]):
        """添加项目列表"""
        self.set_font('Helvetica', '', 10)
        self.set_text_color(51, 51, 51)
        
        for item in items:
            item_text = self._process_text(item)
            self.cell(5, 6, chr(149))  # 项目符号
            self.multi_cell(0, 6, item_text)
        
        self.ln(3)
    
    def add_quote(self, text: str):
        """添加引用块"""
        self.set_fill_color(239, 246, 255)
        self.set_draw_color(59, 130, 246)
        
        # 绘制左边框
        y_start = self.get_y()
        self.set_x(15)
        
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(30, 64, 175)
        
        self.multi_cell(180, 6, self._process_text(text), fill=True)
        
        y_end = self.get_y()
        self.set_line_width(1)
        self.line(12, y_start, 12, y_end)
        
        self.ln(5)


def parse_markdown_content(md_content: str) -> List[Tuple[str, str, any]]:
    """
    解析Markdown内容为结构化元素
    
    Returns:
        List of tuples: (element_type, content, extra_data)
    """
    elements = []
    lines = md_content.split('\n')
    
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        
        # 跳过空行
        if not line:
            i += 1
            continue
        
        # 标题
        if line.startswith('#'):
            level = len(line) - len(line.lstrip('#'))
            title = line.lstrip('#').strip()
            elements.append(('heading', title, level))
            i += 1
            continue
        
        # 表格
        if '|' in line and i + 1 < len(lines) and '---' in lines[i + 1]:
            # 解析表头
            headers = [h.strip() for h in line.split('|') if h.strip()]
            i += 2  # 跳过分隔行
            
            # 解析数据行
            data = []
            while i < len(lines) and '|' in lines[i]:
                row = [c.strip() for c in lines[i].split('|') if c.strip()]
                if row:
                    data.append(row)
                i += 1
            
            elements.append(('table', headers, data))
            continue
        
        # 列表项
        if line.startswith('- ') or line.startswith('* ') or re.match(r'^\d+\.', line):
            items = []
            while i < len(lines):
                l = lines[i].strip()
                if l.startswith('- ') or l.startswith('* '):
                    items.append(l[2:])
                elif re.match(r'^\d+\.', l):
                    items.append(re.sub(r'^\d+\.\s*', '', l))
                elif l and not l.startswith('#') and '|' not in l:
                    # 继续上一个列表项
                    if items:
                        items[-1] += ' ' + l
                else:
                    break
                i += 1
            
            if items:
                elements.append(('list', items, None))
            continue
        
        # 引用
        if line.startswith('>'):
            quote_lines = []
            while i < len(lines) and lines[i].strip().startswith('>'):
                quote_lines.append(lines[i].strip()[1:].strip())
                i += 1
            elements.append(('quote', ' '.join(quote_lines), None))
            continue
        
        # 普通段落
        para_lines = [line]
        i += 1
        while i < len(lines):
            l = lines[i].strip()
            if not l or l.startswith('#') or l.startswith('-') or l.startswith('*') or l.startswith('>') or '|' in l:
                break
            para_lines.append(l)
            i += 1
        
        elements.append(('paragraph', ' '.join(para_lines), None))
    
    return elements


def convert_md_to_pdf(
    md_content: str,
    output_path: Optional[str] = None,
    title: str = "行业研究报告",
    add_cover: bool = True,
    province: str = "",
    industry: str = "",
    year: str = ""
) -> bytes:
    """
    将Markdown内容转换为PDF
    
    Args:
        md_content: Markdown文本内容
        output_path: 输出文件路径（可选）
        title: 报告标题
        add_cover: 是否添加封面
        province: 省份
        industry: 行业
        year: 年份
    
    Returns:
        PDF文件的字节内容
    """
    if not HAS_FPDF:
        raise ImportError("需要安装fpdf2库: pip install fpdf2")
    
    # 创建PDF文档
    pdf = FinSightPDF(title=title)
    
    # 添加封面
    if add_cover:
        pdf.add_cover_page(title, province, industry, year)
    
    # 添加内容页
    pdf.add_page()
    
    # 解析Markdown内容
    elements = parse_markdown_content(md_content)
    
    # 渲染元素
    for elem_type, content, extra in elements:
        try:
            if elem_type == 'heading':
                pdf.add_chapter_title(content, extra)
            elif elem_type == 'paragraph':
                pdf.add_paragraph(content)
            elif elem_type == 'table':
                pdf.add_table(content, extra)
            elif elem_type == 'list':
                pdf.add_bullet_list(content)
            elif elem_type == 'quote':
                pdf.add_quote(content)
        except Exception as e:
            # 跳过渲染失败的元素
            print(f"渲染元素失败: {elem_type}, {e}")
            continue
    
    # 输出PDF
    if output_path:
        pdf.output(output_path)
        with open(output_path, 'rb') as f:
            return f.read()
    else:
        # 输出到临时文件
        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as f:
            temp_path = f.name
        pdf.output(temp_path)
        with open(temp_path, 'rb') as f:
            pdf_bytes = f.read()
        os.unlink(temp_path)
        return pdf_bytes


def convert_md_file_to_pdf(
    md_file_path: str,
    output_path: Optional[str] = None,
    **kwargs
) -> bytes:
    """
    将Markdown文件转换为PDF
    """
    with open(md_file_path, 'r', encoding='utf-8') as f:
        md_content = f.read()
    
    if not output_path:
        output_path = md_file_path.rsplit('.', 1)[0] + '.pdf'
    
    # 从文件名提取信息
    filename = os.path.basename(md_file_path)
    parts = filename.replace('.md', '').split('_')
    
    year = kwargs.get('year', '')
    province = kwargs.get('province', '')
    industry = kwargs.get('industry', '')
    
    if len(parts) >= 3 and not year:
        year = parts[0] if parts[0].isdigit() else ''
    if len(parts) >= 3 and not province:
        province = parts[1] if '省' in parts[1] or '市' in parts[1] else ''
    if len(parts) >= 3 and not industry:
        industry = parts[2] if parts[2] else ''
    
    return convert_md_to_pdf(
        md_content=md_content,
        output_path=output_path,
        year=year,
        province=province,
        industry=industry,
        **kwargs
    )


if __name__ == "__main__":
    # 测试代码
    test_md = """
# Test Report

## Chapter 1: Overview

This is a test paragraph with some content.

### 1.1 Background

| Metric | Value | Note |
|--------|-------|------|
| Market Size | 100B | 2024 |
| Growth Rate | 15% | Annual |

## Chapter 2: Analysis

**Key Finding**: This is an important discovery.

- Point 1
- Point 2
- Point 3

> This is a quote block with important information.
    """
    
    try:
        pdf_bytes = convert_md_to_pdf(
            test_md,
            output_path="test_report.pdf",
            title="Test Report",
            province="Zhejiang",
            industry="AI",
            year="2025"
        )
        print(f"PDF generated successfully, size: {len(pdf_bytes)} bytes")
    except Exception as e:
        print(f"PDF generation failed: {e}")
